#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class Telemetry < ::ProtocolBuffers::Message; end
class TelemetryField < ::ProtocolBuffers::Message; end
class TelemetryGPBTable < ::ProtocolBuffers::Message; end
class TelemetryRowGPB < ::ProtocolBuffers::Message; end

class Telemetry < ::ProtocolBuffers::Message
  set_fully_qualified_name "Telemetry"

  optional :string, :node_id_str, 1
  optional :string, :subscription_id_str, 3
  optional :string, :encoding_path, 6
  optional :uint64, :collection_id, 8
  optional :uint64, :collection_start_time, 9
  optional :uint64, :msg_timestamp, 10
  repeated ::TelemetryField, :data_gpbkv, 11
  optional ::TelemetryGPBTable, :data_gpb, 12
  optional :uint64, :collection_end_time, 13
end

class TelemetryField < ::ProtocolBuffers::Message
  set_fully_qualified_name "TelemetryField"

  optional :uint64, :timestamp, 1
  optional :string, :name, 2
  optional :bytes, :bytes_value, 4
  optional :string, :string_value, 5
  optional :bool, :bool_value, 6
  optional :uint32, :uint32_value, 7
  optional :uint64, :uint64_value, 8
  optional :sint32, :sint32_value, 9
  optional :sint64, :sint64_value, 10
  optional :double, :double_value, 11
  optional :float, :float_value, 12
  repeated ::TelemetryField, :tables, 15
end

class TelemetryGPBTable < ::ProtocolBuffers::Message
  set_fully_qualified_name "TelemetryGPBTable"

  repeated ::TelemetryRowGPB, :row, 1
end

class TelemetryRowGPB < ::ProtocolBuffers::Message
  set_fully_qualified_name "TelemetryRowGPB"

  optional :uint64, :timestamp, 1
  optional :bytes, :keys, 10
  optional :bytes, :content, 11
end

